print('Python과 Ruby공통 : ceil은 반올림,floor는 내림')
print("Python에서 복잡한 사칙연산을 할 때는 가장 위에 import math를 입력해야 함")
print("Python에서는 'math ceil(2.24)'와 같은 형식으로 입력해야 함")
print('Ruby에서는 "puts(2.24.floor())"와 같은 형식으로 입력해야 함')
print('hello '+'world')
print('python '*3)
print('hello' [1], '<-hello의 2번째 문자 추출. []를 이용해서 특정 문자를 추출할 수 있음')